apiVersion: v1
kind: Pod
metadata:
  name: flox-file-appender
  labels:
    app: flox
spec:
  restartPolicy: Never
  volumes:
    - name: logs
      emptyDir: {}
  containers:
    - name: file-appender
      image: curlimages/curl:latest
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: logs
          mountPath: /var/log
      command: ["/bin/sh", "-c"]
      args:
      - |
        while true; do
          echo "{\"msg\":\"test $(date +%T)\", \"level\":\"info\", \"password\":\"1234\""} >> /var/log/app.log;
          echo " - written";
          sleep 5;
        done
