apiVersion: v1
kind: Pod
metadata:
  name: kcat
  labels:
    app: kcat
spec:
  restartPolicy: Never
  containers:
    - name: kcat
      image: confluentinc/cp-kcat:latest
      command: ["sh", "-c", "sleep infinity"]

