apiVersion: v1
kind: Pod
metadata:
  name: log-writer
  labels:
    app: log-writer
spec:
  restartPolicy: Never
  containers:
    - name: log-writer
      image: bash
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            echo "{\"msg\":\"log from $(hostname)\", \"level\":\"info\", \"password\":\"123\", \"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}";
            sleep 5;
          done
