name: Go Test

on:
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
  push:
    branches: ["main"]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'

    - name: Run Tests
      run: |
        go mod tidy
        go test ./... -v
